name: Semantic Pull Request

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build:
    uses: The-FireHub-Project-legacy/.github/.github/workflows/SemanticPullRequest.yml@master
    with:
      repo-type: core-standard
      php-version: "8.2"
      test: |
        bug
        critical
        feature
        debug
        development
        docs
        fix
        incident
        security
        maintenance
        optimization
        performance
        question
        support
        suggestions
        enhancement
        refactor
        testing
        internal
        revert
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
